

//redux saga test action types
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'


//invite saga action types
export const INVITING_DATA = 'INVITING_DATA'
export const INVITING_DATA_SUCCESS = 'INVITING_DATA_SUCCESS'
export const INVITING_DATA_FAILURE = 'INVITING_DATA_FAILURE'


// profile saga action types
export const FETCHING_PROFILE = "FETCHING_PROFILE";
export const FETCHING_PROFILE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_PROFILE_FAILURE = "FETCHING_PROFILE_FAILURE";

// profile saga action types
export const FETCHING_CONVERSATION = "FETCHING_CONVERSATION";
export const FETCHING_CONVERSATION_SUCCESS = "FETCHING_CONVERSATION_SUCCESS";
export const FETCHING_CONVERSATION_FAILURE = "FETCHING_CONVERSATION_FAILURE";
